spring:
  application:
    name: spring-cloud-gateway

#Spring Cloud Api Gateway
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/restaurant/**
        - id: ORDER-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
        - id: CUSTOMER-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/customer/**
        - id: PAYMENT-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/payment/**
        - id: RESTAURANT-OWNER-SERVICE
          uri: http://localhost:8086
          predicates:
            - Path=/owner/**
        - id: DELIVERY-PARTNER-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/partner/**

#Eureka Client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

#Port
# server:
#   port: 9000
